### ISSUE TITLE
Errors after a successful enhancement to PEN

### ISSUE THREAD

**Issue by AndiSlash0723** [25/EnchantmentsEnhance#102]
大约是这样的0.0
我在用的版本是 7.2.0 (#390)

刚刚成功强化至东(PEN)之后发​​现强化界面变成了这样 :
https://imgur.com/a/KQgP0me

之后 伺服器那边也跑出了错误0.0 :
https://imgur.com/a/7X7ogT4

有个小提议的 打算另开一个issue再讲述 ^.^

**Comment by 25** [comment]
```
java.lang.ArrayIndexOutOfBoundsException: 21
        at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.update(MainMenu.java:200) ~[?:?]
        at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu$1.run(MainMenu.java:116) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit-1.12.jar:git-Bukkit-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [craftbukkit-1.12.jar:git-Bukkit-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:689) [craftbukkit-1.12.jar:git-Bukkit-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:370) [craftbukkit-1.12.jar:git-Bukkit-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:650) [craftbukkit-1.12.jar:git-Bukkit-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit-1.12.jar:git-Bukkit-9a1fc1e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```
