### ISSUE TITLE
Failed to check version

### ISSUE THREAD

**Issue by 25** [25/EnchantmentsEnhance#107]
```
[02:21:01 INFO]: [EnchantmentsEnhance] Updating config to the latest...
[02:21:01 INFO]: [EnchantmentsEnhance] Found 549 config settings
[02:21:01 INFO]: [EnchantmentsEnhance] Added 0 new config settings
[02:21:01 INFO]: [EnchantmentsEnhance] Updating enchantments to the latest...
[02:21:01 INFO]: [EnchantmentsEnhance] Found 293 enchantment settings
[02:21:01 INFO]: [EnchantmentsEnhance] Added 0 new enchantment settings
[02:21:01 ERROR]: Error occurred while enabling EnchantmentsEnhance v7.2.0 (Is it up to date?)
java.net.UnknownHostException: api.spigotmc.org
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[?:1.8.0_192]
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_192]
at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_192]
at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666) ~[?:1.8.0_192]
at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) ~[?:1.8.0_192]
at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:1.8.0_192]
at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_192]
at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_192]
at sun.net.www.protocol.https.HttpsClient.(HttpsClient.java:264) ~[?:1.8.0_192]
at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[?:1.8.0_192]
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:1.8.0_192]
at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[?:1.8.0_192]
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:1.8.0_192]
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:1.8.0_192]
at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334) ~[?:1.8.0_192]
at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309) ~[?:1.8.0_192]
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259) ~[?:1.8.0_192]
at org.pixeltime.enchantmentsenhance.version.VersionManager$Companion.getLatestVersion(VersionManager.kt:41) ~[?:?]
at org.pixeltime.enchantmentsenhance.version.VersionManager$Companion.isUpToDate(VersionManager.kt:47) ~[?:?]
at org.pixeltime.enchantmentsenhance.version.VersionManager.isUpToDate(VersionManager.kt) ~[?:?]
at org.pixeltime.enchantmentsenhance.Main.onEnable(Main.java:182) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-488]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.2.jar:git-Paper-488]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-488]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-488]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-488]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.2.jar:git-Paper-488]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.2.jar:git-Paper-488]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.2.jar:git-Paper-488]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-488]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-488]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
[02:21:01 INFO]: [EnchantmentsEnhance] Disabling EnchantmentsEnhance v7.2.0
[02:21:01 INFO]: 强化插件已禁用!
```

**Comment by 25** [comment]
Switch our own version dependencies to ldk-bukkit-version @lgou2w
