### ISSUE TITLE
Renamed jar file containing unicode crashes plugin

### ISSUE THREAD

**Issue by 25** [25/EnchantmentsEnhance#108]
```
[17:30:41 ERROR]: Error occurred while enabling EnchantmentsEnhance v7.1.0 (Is it up to date?)
java.lang.RuntimeException: Unexpected IOException reading JAR File '/D:/Plugin-testing/1.13/plugins/%5B强化%5DEnchantmentsEnhance-Plugin-7.1.0.jar'. Do you have strange characters in your folders? Such as #?
        at org.pixeltime.enchantmentsenhance.util.ClassGetter.processJarfile(ClassGetter.java:62) ~[?:?]
        at org.pixeltime.enchantmentsenhance.util.ClassGetter.getClassesForPackage(ClassGetter.java:39) ~[?:?]
        at org.pixeltime.enchantmentsenhance.manager.PackageManager.initializeAll(PackageManager.java:51) ~[?:?]
        at org.pixeltime.enchantmentsenhance.Main.onEnable(Main.java:221) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.io.FileNotFoundException: D:\Plugin-testing\1.13\plugins\%5B强化%5DEnchantmentsEnhance-Plugin-7.1.0.jar (The system cannot find the file specified)
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_201]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_201]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_201]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_201]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_201]
        at org.pixeltime.enchantmentsenhance.util.ClassGetter.processJarfile(ClassGetter.java:60) ~[?:?]
        ... 14 more
```

**Comment by lgou2w** [comment]
What is the function of this `ClassGetter` ?

**Comment by 25** [comment]
Use Java reflection to find all classes in a package.
