### ISSUE TITLE
error

### ISSUE THREAD

**Issue by LordRamma** [25/EnchantmentsEnhance#174]
[20:22:17] [Server thread/ERROR]: Could not pass event InventoryClickEvent to EnchantmentsEnhance v7.9.3
java.lang.UnsupportedOperationException: Illegal item type 'AIR' that does not supported.
	at com.lgou2w.ldk.bukkit.item.ItemFactory.readTag(ItemFactory.kt:198) ~[?:?]
	at com.lgou2w.ldk.bukkit.item.ItemFactory.readTagSafe(ItemFactory.kt:178) ~[?:?]
	at org.pixeltime.enchantmentsenhance.manager.ItemManager.getToolEnchantLevel(ItemManager.java:100) ~[?:?]
	at org.pixeltime.enchantmentsenhance.listener.AnvilRestrict.onInventoryClick(AnvilListener.kt:18) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor793.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-235]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-235]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-235]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2314) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1088) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-235]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by 25** [comment]
Plugin version?

**Comment by 25** [comment]
Related to https://github.com/25/EnchantmentsEnhance/issues/167

**Comment by LordRamma** [comment]
This error appears when using on the enchantment table (vanilla) an EmeraldTools plugin item (https://www.spigotmc.org/resources/emerald-tools.59681/) ... can solve the problem?

**Comment by LordRamma** [comment]
I can not solve the problem, I will send all my files, please help me!

**Comment by LordRamma** [comment]
Enchantments.yml 
https://pastebin.com/VxH5TrYD
lang.yml
https://pastebin.com/tc0Cq6yU
config.yml
https://pastebin.com/w9b3mcYs

**Comment by LordRamma** [comment]
version minecraft 1.14.4
version plugin: 7.9.3 (premium)
https://www.spigotmc.org/resources/50-off-enchantmentsenhancepro-gear-progression-mechanics-with-customized-enchantments.59555/

**Comment by lgou2w** [comment]
@25 See below:
https://github.com/25/EnchantmentsEnhance/blob/14f052dca379990432b56dc378ad68922c6355ad/modules/EnchantmentsEnhance-Plugin/src/main/java/org/pixeltime/enchantmentsenhance/manager/ItemManager.java#L99-L103

**Comment by lgou2w** [comment]
The source of the error should be here. Line 17:
No judgment item is `null` or `air` !

https://github.com/25/EnchantmentsEnhance/blob/14f052dca379990432b56dc378ad68922c6355ad/modules/EnchantmentsEnhance-Plugin/src/main/kotlin/org/pixeltime/enchantmentsenhance/listener/AnvilListener.kt#L17-L18

**Comment by LordRamma** [comment]
ERROR Could not pass event InventoryClickEvent to EnchantmentsEnhance v7.9.3
22.12 22:26:19 [Server] INFO java.lang.UnsupportedOperationException: Illegal item type 'AIR' that does not supported.
22.12 22:26:19 [Server] INFO at com.lgou2w.ldk.bukkit.item.ItemFactory.readTag(ItemFactory.kt:198) ~[?:?]
22.12 22:26:19 [Server] INFO at com.lgou2w.ldk.bukkit.item.ItemFactory.readTagSafe(ItemFactory.kt:178) ~[?:?]
22.12 22:26:19 [Server] INFO at org.pixeltime.enchantmentsenhance.manager.ItemManager.getToolEnchantLevel(ItemManager.java:100) ~[?:?]
22.12 22:26:19 [Server] INFO at org.pixeltime.enchantmentsenhance.listener.AnvilRestrict.onInventoryClick(AnvilListener.kt:18) ~[?:?]
22.12 22:26:19 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor806.execute(Unknown Source) ~[?:?]
22.12 22:26:19 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-235]
22.12 22:26:19 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-235]
22.12 22:26:19 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-235]
22.12 22:26:19 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-235]
22.12 22:26:19 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2314) ~[patched_1.14.4.jar:git-Paper-235]
22.12 22:26:19 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-235]
22.12 22:26:19 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-235]
22.12 22:26:19 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-235]
22.12 22:26:19 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-235]
22.12 22:26:19 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-235]
22.12 22:26:19 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-235]
22.12 22:26:19 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-235]
22.12 22:26:19 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-235]
22.12 22:26:19 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-235]
22.12 22:26:19 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-235]
22.12 22:26:19 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1158) ~[patched_1.14.4.jar:git-Paper-235]
22.12 22:26:19 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-235]
22.12 22:26:19 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
