### ISSUE TITLE
Error while starting up in 6.5.0

### ISSUE THREAD

**Issue by JaVolimKatarinu** [25/EnchantmentsEnhance#48]
### What behaviour is observed:
What was the error?
I dont know, it just gave me a error while starting up.

### Steps to reproduce:
How did you cause the issue?
By downloading newest version, 6.5.0

### Plugin list:
This can be found by running `/pl`
Plugins (31): LuckPerms, WorldEdit, Questioner, ServerTutorialPlus, ParrotAnnouncer, Lands, HolographicDisplays, Votifier, AdvancedMultiLanguage, WorldGuard, VotingPlugin, DangerousCaves, Ridables, VillageDefense, Vault, TokenManager, Essentials, EnchantmentsEnhance, Jobs, Citizens, EssentialsProtect, AdvancedAchievements, EssentialsChat, EssentialsGeoIP, EssentialsAntiBuild, MineSync, EssentialsSpawn, CitizensText, Towny, TownyChat, TownyNameUpdater

### Environment description
What server and version?
This server is running CraftBukkit version git-Spigot-1503de9-200b239 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

### Enchantments Enhance build number:
This can be found by running `/enhance version`
12:09:23

[EnchantmentsEnhance] You are using EnchantmentsEnhance v6.5.0

### Error Log:
Link of the error log or stacktrace (if any, full log preferred)
ERROR
16. 09. 2018. 12:04:36
12:04:36
Error occurred while enabling EnchantmentsEnhance v6.5.0 (Is it up to date?)
Console
16. 09. 2018. 12:04:36
12:04:36

java.lang.NullPointerException: null
at org.pixeltime.enchantmentsenhance.manager.DropManager$Companion.setUp(DropManager.kt:36) ~[?:?]
at org.pixeltime.enchantmentsenhance.manager.DropManager.setUp(DropManager.kt) ~[?:?]
at org.pixeltime.enchantmentsenhance.Main.onEnable(Main.java:217) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-1503de9-200b239]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot.jar:git-Spigot-1503de9-200b239]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-1503de9-200b239]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:425) [spigot.jar:git-Spigot-1503de9-200b239]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:339) [spigot.jar:git-Spigot-1503de9-200b239]
at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [spigot.jar:git-Spigot-1503de9-200b239]
at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [spigot.jar:git-Spigot-1503de9-200b239]
at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [spigot.jar:git-Spigot-1503de9-200b239]
at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot.jar:git-Spigot-1503de9-200b239]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot.jar:git-Spigot-1503de9-200b239]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

**Comment by 25** [comment]
Could you please try [Experimental Build 1](http://soulbound.me/job/EnchantmentsEnhance_Experimental/)?
Post any errors when you try to use this build.

**Comment by 25** [comment]
Config structure has been updated: https://github.com/25/EnchantmentsEnhance/blob/master/EnchantmentsEnhance-Core/src/resources/config.yml#L106
You could remove GLOWING_REDSTONE_ORE from the list.

Thank you for reporting this bug! I will implement a system which prevents config changes from causing errors.
