### ISSUE TITLE
请教一个关于空指针异常的问题

### ISSUE THREAD

**Issue by yeguanglingyue** [25/EnchantmentsEnhance#51]
### What behaviour is observed:
使用enhance menu指令时，发生空指针异常报错，报错日志填在下面了；

由于本人源码渣实在不知道是哪里出了问题，今天一早把插件从6.3.0升级到6.5.0以后就出现问题了，无论怎么调整都会报错，删除config等文件重新加载或者将插件版本退回到6.3.0都会报错。希望大佬有空帮忙解决一下awa

### Plugin list:
This can be found by running `/pl`

### Environment description
spigot-1.13.1

### Enchantments Enhance build number:
6.5.0

### Error Log:
[16:33:02] [Server thread/INFO]: yeyue issued server command: /enhance menu
[16:33:02] [Server thread/WARN]: java.lang.NullPointerException
[16:33:02] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.menu.icons.ItemIcon.getItem(ItemIcon.java:58)
[16:33:02] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.update(MainMenu.java:261)
[16:33:02] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.<init>(MainMenu.java:82)
[16:33:02] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.command.player.MenuCommand.onCommand(MenuCommand.kt:32)
[16:33:02] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.manager.CommandManager.onCommand(CommandManager.java:135)
[16:33:02] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:33:02] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[16:33:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:675)
[16:33:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1585)
[16:33:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1445)
[16:33:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(SourceFile:37)
[16:33:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(SourceFile:9)
[16:33:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[16:33:02] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[16:33:02] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[16:33:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[16:33:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:839)
[16:33:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:376)
[16:33:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:792)
[16:33:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:695)
[16:33:02] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:33:06] [Server thread/INFO]: yeyue lost connection: Disconnected
[16:33:07] [Server thread/WARN]: java.lang.NullPointerException
[16:33:07] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.mysql.DataStorage.saveStats(DataStorage.java:70)
[16:33:07] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.listener.PlayerStreamListener$1.run(PlayerStreamListener.java:80)
[16:33:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:58)
[16:33:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:360)
[16:33:07] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:833)
[16:33:07] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:376)
[16:33:07] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:792)
[16:33:07] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:695)
[16:33:07] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by 25** [comment]
下载[实验构建#2](http://soulbound.me/job/EnchantmentsEnhance_Experimental/2/)
