### ISSUE TITLE
打開附魔臺時出現錯誤

### ISSUE THREAD

**Issue by Aki404** [25/EnchantmentsEnhance#62]
[00:35:41 ERROR]: Could not pass event PlayerInteractEvent to EnchantmentsEnhance v6.8.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-19c3c5a-5932f8a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-19c3c5a-5932f8a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-19c3c5a-5932f8a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-19c3c5a-5932f8a]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:299) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:457) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1237) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-19c3c5a-5932f8a]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-19c3c5a-5932f8a]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
        at org.pixeltime.enchantmentsenhance.gui.Clickable.getGlowingItem(Clickable.java:28) ~[%5B黑石武器%5DEnchantmentsEnhance-1.13-6.8.0.jar:6.8.0]
        at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.update(MainMenu.java:280) ~[%5B黑石武器%5DEnchantmentsEnhance-1.13-6.8.0.jar:6.8.0]
        at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.<init>(MainMenu.java:82) ~[%5B黑石武器%5DEnchantmentsEnhance-1.13-6.8.0.jar:6.8.0]
        at org.pixeltime.enchantmentsenhance.listener.VanillaEnchantListener.onOpenEnchantmentTable(VanillaEnchantListener.java:43) ~[%5B黑石武器%5DEnchantmentsEnhance-1.13-6.8.0.jar:6.8.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-19c3c5a-5932f8a]
        ... 17 more

**Comment by 25** [comment]
你下载的是1.8版本，但是你的服务器是1.13.2
