### ISSUE TITLE
Randomly /shop inventory stops working

### ISSUE THREAD

**Issue by stsguitar23** [25/EnchantmentsEnhance#63]
### What behaviour is observed:
Randomly /enhance inventory will stop working

### Steps to reproduce:
start server, wait a little bit. use /shop inventory

### Plugin list:
cratesplus, luckperms, worldedit, moblimiter, keepitems, minepacks, worldborder, votifier, vault, essentials, rankip, epicrename, towny, jobs, quantumshop, supervanish, ultimatekits

### Environment description
Latest spigot 1.13.2 minecraft

### Enchantments Enhance build number:
v6.8.0

### Error Log:

[WARNING] [EnchantmentsEnhance] Plugin EnchantmentsEnhance v6.8.0 generated an exception while executing task 12833

java.lang.NullPointerException: null

at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-d5e9688]

at org.pixeltime.enchantmentsenhance.util.Util.toColor(Util.java:137) ~[?:?]

at org.pixeltime.enchantmentsenhance.util.ItemBuilder.setName(ItemBuilder.java:117) ~[?:?]

at org.pixeltime.enchantmentsenhance.gui.menu.icons.StoneIcon.getItem(StoneIcon.java:38) ~[?:?]

at org.pixeltime.enchantmentsenhance.gui.menu.ItemMenu.update(ItemMenu.java:66) ~[?:?]

at org.pixeltime.enchantmentsenhance.gui.menu.ItemMenu.<init>(ItemMenu.java:51) ~[?:?]

at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu$3.run(MainMenu.java:266) ~[?:?]

at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-d5e9688]

at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar:git-Spigot-b0f4c22-d5e9688]

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]

**Comment by stsguitar23** [comment]
[WARNING] java.lang.NullPointerException

[WARNING] at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324)

[WARNING] at org.pixeltime.enchantmentsenhance.util.Util.toColor(Util.java:137)

[WARNING] at org.pixeltime.enchantmentsenhance.util.ItemBuilder.setName(ItemBuilder.java:117)

[WARNING] at org.pixeltime.enchantmentsenhance.gui.menu.icons.StoneIcon.getItem(StoneIcon.java:38)

[WARNING] at org.pixeltime.enchantmentsenhance.gui.menu.ItemMenu.update(ItemMenu.java:66)

[WARNING] at org.pixeltime.enchantmentsenhance.gui.menu.ItemMenu.<init>(ItemMenu.java:51)

[WARNING] at org.pixeltime.enchantmentsenhance.command.player.InventoryCommand.onCommand(InventoryCommand.kt:32)

[WARNING] at org.pixeltime.enchantmentsenhance.manager.CommandManager.onCommand(CommandManager.java:135)

[WARNING] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)

[WARNING] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)

[WARNING] at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704)

[WARNING] at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636)

[WARNING] at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476)

[WARNING] at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)

[WARNING] at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)

[WARNING] at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)

[WARNING] at net.minecraft.server.v1_13_R2.PlayerConnectionUtils$$Lambda$2421.00000000280F2AB0.run(Unknown Source)

[WARNING] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[WARNING] at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[WARNING] at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)

[WARNING] at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896)

[WARNING] at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)

[WARNING] at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)

[WARNING] at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)

[WARNING] at java.lang.Thread.run(Thread.java:813)

**Comment by 25** [comment]
Try this build: [Download](http://www.soulbound.me/job/EnchantmentsEnhance_Stable/304/)
