### ISSUE TITLE
java reflection error, spigot1.12.2

### ISSUE THREAD

**Issue by cvczcvc** [25/EnchantmentsEnhance#66]
[21:55:11] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[21:55:11] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:55:11] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:55:11] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:55:11] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:55:11] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.manager.modular.GlowItem_Unsafe.addGlow(GlowItem_Unsafe.java:33)
[21:55:11] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.Clickable.getGlowingItem(Clickable.java:28)
[21:55:11] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.update(MainMenu.java:280)
[21:55:11] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.<init>(MainMenu.java:82)
[21:55:11] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.listener.VanillaEnchantListener.onOpenEnchantmentTable(VanillaEnchantListener.java:43)
[21:55:11] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source)
[21:55:11] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:55:11] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:55:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[21:55:11] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:55:11] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[21:55:11] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[21:55:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235)
[21:55:11] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458)
[21:55:11] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951)
[21:55:11] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[21:55:11] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
[21:55:11] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[21:55:11] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[21:55:11] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[21:55:11] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[21:55:11] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[21:55:11] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[21:55:11] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[21:55:11] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[21:55:11] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:55:11] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodError: org.bukkit.enchantments.EnchantmentWrapper.<init>(Ljava/lang/String;)V
[21:55:11] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.<init>(UnsafeGlow.java:39)
[21:55:11] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.getGlow(UnsafeGlow.java:54)
[21:55:11] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.addGlow(UnsafeGlow.java:63)
[21:55:11] [Server thread/WARN]: 	... 30 more
[21:55:19] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[21:55:19] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:55:19] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.manager.modular.GlowItem_Unsafe.addGlow(GlowItem_Unsafe.java:33)
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.Clickable.getGlowingItem(Clickable.java:28)
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.update(MainMenu.java:238)
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.menu.handlers.MenuHandler.onClick(MenuHandler.java:58)
[21:55:19] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:55:19] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[21:55:19] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:55:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[21:55:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[21:55:19] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[21:55:19] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:55:19] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodError: org.bukkit.enchantments.EnchantmentWrapper.<init>(Ljava/lang/String;)V
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.<init>(UnsafeGlow.java:39)
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.getGlow(UnsafeGlow.java:54)
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.addGlow(UnsafeGlow.java:63)
[21:55:19] [Server thread/WARN]: 	... 28 more
[21:55:19] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[21:55:19] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:55:19] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.manager.modular.GlowItem_Unsafe.addGlow(GlowItem_Unsafe.java:33)
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.menu.icons.StatsIcon.getItem(StatsIcon.java:47)
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.update(MainMenu.java:246)
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.menu.handlers.MenuHandler.onClick(MenuHandler.java:58)
[21:55:19] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:55:19] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[21:55:19] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:55:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[21:55:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[21:55:19] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[21:55:19] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:55:19] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodError: org.bukkit.enchantments.EnchantmentWrapper.<init>(Ljava/lang/String;)V
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.<init>(UnsafeGlow.java:39)
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.getGlow(UnsafeGlow.java:54)
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.addGlow(UnsafeGlow.java:63)
[21:55:19] [Server thread/WARN]: 	... 28 more
[21:55:19] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[21:55:19] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:55:19] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.manager.modular.GlowItem_Unsafe.addGlow(GlowItem_Unsafe.java:33)
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.Clickable.getGlowingItem(Clickable.java:28)
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.update(MainMenu.java:280)
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.menu.handlers.MenuHandler.onClick(MenuHandler.java:58)
[21:55:19] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:55:19] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[21:55:19] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:55:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[21:55:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[21:55:19] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[21:55:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[21:55:19] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:55:19] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodError: org.bukkit.enchantments.EnchantmentWrapper.<init>(Ljava/lang/String;)V
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.<init>(UnsafeGlow.java:39)
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.getGlow(UnsafeGlow.java:54)
[21:55:19] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.addGlow(UnsafeGlow.java:63)
[21:55:19] [Server thread/WARN]: 	... 28 more
[21:55:21] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[21:55:21] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:55:21] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.manager.modular.GlowItem_Unsafe.addGlow(GlowItem_Unsafe.java:33)
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.Clickable.getGlowingItem(Clickable.java:28)
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.update(MainMenu.java:238)
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.GUIListener.onClick(GUIListener.java:58)
[21:55:21] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:55:21] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[21:55:21] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:55:21] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[21:55:21] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[21:55:21] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[21:55:21] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:55:21] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodError: org.bukkit.enchantments.EnchantmentWrapper.<init>(Ljava/lang/String;)V
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.<init>(UnsafeGlow.java:39)
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.getGlow(UnsafeGlow.java:54)
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.addGlow(UnsafeGlow.java:63)
[21:55:21] [Server thread/WARN]: 	... 28 more
[21:55:21] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[21:55:21] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:55:21] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.manager.modular.GlowItem_Unsafe.addGlow(GlowItem_Unsafe.java:33)
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.menu.icons.StatsIcon.getItem(StatsIcon.java:47)
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.update(MainMenu.java:246)
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.GUIListener.onClick(GUIListener.java:58)
[21:55:21] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:55:21] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[21:55:21] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:55:21] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[21:55:21] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[21:55:21] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[21:55:21] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:55:21] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodError: org.bukkit.enchantments.EnchantmentWrapper.<init>(Ljava/lang/String;)V
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.<init>(UnsafeGlow.java:39)
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.getGlow(UnsafeGlow.java:54)
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.addGlow(UnsafeGlow.java:63)
[21:55:21] [Server thread/WARN]: 	... 28 more
[21:55:21] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[21:55:21] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:55:21] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.manager.modular.GlowItem_Unsafe.addGlow(GlowItem_Unsafe.java:33)
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.Clickable.getGlowingItem(Clickable.java:28)
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.update(MainMenu.java:280)
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.gui.GUIListener.onClick(GUIListener.java:58)
[21:55:21] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:55:21] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[21:55:21] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:55:21] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[21:55:21] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[21:55:21] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[21:55:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[21:55:21] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:55:21] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodError: org.bukkit.enchantments.EnchantmentWrapper.<init>(Ljava/lang/String;)V
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.<init>(UnsafeGlow.java:39)
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.getGlow(UnsafeGlow.java:54)
[21:55:21] [Server thread/WARN]: 	at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.addGlow(UnsafeGlow.java:63)
[21:55:21] [Server thread/WARN]: 	... 28 more

**Comment by 25** [comment]
[下载构建](http://www.soulbound.me/job/EnchantmentsEnhance_Stable/314/)
