### ISSUE TITLE
Sorry! Another One XD

### ISSUE THREAD

**Issue by Krauzzer** [25/EnchantmentsEnhance#7]
### What behaviour is observed:
You can take items that are part of the gui.
 Edit01- It only happens when using the enchanting table. The menu command works.

### What behaviour is expected:
The items returning to their position inside the gui.

### Steps/models to reproduce:
Just click it and place on your inventory

### Plugin list:
Not needed i guess

### Environment description
Latest

### Enchantments Enhance build number:
Latest

### Error Log:
Maybe that log is from the plugin, I don't know...

```
23:04:47 [FATAL] Error executing task
23:04:47 java.util.concurrent.ExecutionException: java.lang.AssertionError: TRAP
23:04:49 at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_172]
23:04:50 at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_172]
23:04:50 at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:47) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
23:04:51 at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
23:04:52 at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
23:04:53 at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
23:04:53 at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
23:04:53 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
23:04:53 Caused by: java.lang.AssertionError: TRAP
23:04:53 at net.minecraft.server.v1_12_R1.ItemStack.F(ItemStack.java:100) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
23:04:53 at net.minecraft.server.v1_12_R1.ItemStack.setCount(ItemStack.java:839) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
23:04:53 at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:413) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
23:04:53 at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1004) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
23:04:54 at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
23:04:54 at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
23:04:54 at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
23:04:54 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_172]
23:04:55 at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_172]
23:04:55 at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
23:04:55 ... 5 more
```

**Comment by 25** [comment]
Hey, the reported glitches are fixed, and I don't think the error log relates to this repository.

Thanks!

**Comment by 25** [comment]
Investigating gui issues.
