### ISSUE TITLE
In-game item duplication

### ISSUE THREAD

**Issue by 25** [25/EnchantmentsEnhance#88]
LordRamma: A player was able to duplicate an item. After failing and achieving success, another sword appeared in the inventory when closing the menu.

```
WARN java.lang.reflect.InvocationTargetException
28.02 10:38:35 [Server] WARN at sun.reflect.GeneratedMethodAccessor148.invoke(Unknown Source)
28.02 10:38:35 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
28.02 10:38:35 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
28.02 10:38:35 [Server] WARN at org.pixeltime.enchantmentsenhance.manager.modular.GlowItem_Unsafe.addGlow(GlowItem_Unsafe.java:33)
28.02 10:38:35 [Server] WARN at org.pixeltime.enchantmentsenhance.gui.menu.icons.ItemIcon.getItem(ItemIcon.java:62)
28.02 10:38:35 [Server] WARN at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.update(MainMenu.java:263)
28.02 10:38:35 [Server] WARN at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.<init>(MainMenu.java:82)
28.02 10:38:35 [Server] WARN at org.pixeltime.enchantmentsenhance.listener.VanillaEnchantListener.onOpenEnchantmentTable(VanillaEnchantListener.java:48)
28.02 10:38:35 [Server] WARN at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor640.execute(Unknown Source)
28.02 10:38:35 [Server] WARN at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
28.02 10:38:35 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
28.02 10:38:35 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
28.02 10:38:35 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
28.02 10:38:35 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:320)
28.02 10:38:35 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:287)
28.02 10:38:35 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:110)
28.02 10:38:35 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1285)
28.02 10:38:35 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40)
28.02 10:38:35 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10)
28.02 10:38:35 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
28.02 10:38:35 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
28.02 10:38:35 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
28.02 10:38:35 [Server] WARN at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
28.02 10:38:35 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011)
28.02 10:38:35 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
28.02 10:38:35 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
28.02 10:38:35 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
28.02 10:38:35 [Server] WARN at java.lang.Thread.run(Thread.java:748)
28.02 10:38:35 [Server] WARN Caused by: java.lang.NoSuchMethodError: org.bukkit.enchantments.EnchantmentWrapper.<init>(I)V
28.02 10:38:37 [Multicraft] Skipped 38 lines due to rate limit (30/s)
28.02 10:38:37 [Server] WARN java.lang.reflect.InvocationTargetException
28.02 10:38:37 [Server] WARN at sun.reflect.GeneratedMethodAccessor148.invoke(Unknown Source)
28.02 10:38:37 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
28.02 10:38:37 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
28.02 10:38:37 [Server] WARN at org.pixeltime.enchantmentsenhance.manager.modular.GlowItem_Unsafe.addGlow(GlowItem_Unsafe.java:33)
28.02 10:38:37 [Server] WARN at org.pixeltime.enchantmentsenhance.gui.menu.icons.ItemIcon.getItem(ItemIcon.java:62)
28.02 10:38:37 [Server] WARN at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.update(MainMenu.java:263)
28.02 10:38:37 [Server] WARN at org.pixeltime.enchantmentsenhance.gui.GUIListener.onClick(GUIListener.java:58)
28.02 10:38:37 [Server] WARN at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor645.execute(Unknown Source)
28.02 10:38:37 [Server] WARN at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
28.02 10:38:37 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
28.02 10:38:37 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
28.02 10:38:37 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
28.02 10:38:37 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2301)
28.02 10:38:37 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33)
28.02 10:38:37 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10)
28.02 10:38:37 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
28.02 10:38:37 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
28.02 10:38:37 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
28.02 10:38:37 [Server] WARN at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
28.02 10:38:37 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011)
28.02 10:38:37 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
28.02 10:38:37 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
28.02 10:38:37 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
28.02 10:38:37 [Server] WARN at java.lang.Thread.run(Thread.java:748)
28.02 10:38:37 [Server] WARN Caused by: java.lang.NoSuchMethodError: org.bukkit.enchantments.EnchantmentWrapper.<init>(I)V
28.02 10:38:37 [Server] WARN at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.<init>(UnsafeGlow.java:40)
28.02 10:38:37 [Server] WARN at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.getGlow(UnsafeGlow.java:55)
28.02 10:38:37 [Server] WARN at org.pixeltime.enchantmentsenhance.util.UnsafeGlow.addGlow(UnsafeGlow.java:64)
28.02 10:38:37 [Server] WARN ... 24 more
```

**Comment by lgou2w** [comment]
The `EnchantmentWrapper` after 1.13 is no longer an `id` constructor.

**Comment by 25** [comment]
```
WARN [EnchantmentsEnhance] Plugin EnchantmentsEnhance v7.1.0 generated an exception while executing task 4757
28.02 18:53:22 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: -1
28.02 18:53:22 [Server] INFO at java.util.ArrayList.fastRemove(ArrayList.java:546) ~[?:1.8.0_144]
28.02 18:53:22 [Server] INFO at java.util.ArrayList.remove(ArrayList.java:529) ~[?:1.8.0_144]
28.02 18:53:22 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerInventory.onClose(PlayerInventory.java:51) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at net.minecraft.server.v1_13_R2.Container.transferTo(Container.java:38) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1192) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at net.minecraft.server.v1_13_R2.EntityPlayer.closeInventory(EntityPlayer.java:1031) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:517) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu$3.run(MainMenu.java:267) ~[?:?]
28.02 18:53:22 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
28.02 18:53:22 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
28.02 18:53:22 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
28.02 18:53:22 [Server] WARN [EnchantmentsEnhance] Plugin EnchantmentsEnhance v7.1.0 generated an exception while executing task 4722
28.02 18:53:22 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: -1
28.02 18:53:22 [Server] INFO at java.util.ArrayList.add(ArrayList.java:459) ~[?:1.8.0_144]
28.02 18:53:22 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerInventory.onOpen(PlayerInventory.java:47) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at net.minecraft.server.v1_13_R2.Container.transferTo(Container.java:40) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1192) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at net.minecraft.server.v1_13_R2.EntityPlayer.closeInventory(EntityPlayer.java:1031) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:517) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu$3.run(MainMenu.java:267) ~[?:?]
28.02 18:53:22 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
```

**Comment by lgou2w** [comment]
This is because the underlying uses a non-thread safe collection.

**Comment by lgou2w** [comment]
Glow enchantment problem see #90 .
