### ISSUE TITLE
Non-thread safe collection

### ISSUE THREAD

**Issue by 25** [25/EnchantmentsEnhance#91]
```
WARN [EnchantmentsEnhance] Plugin EnchantmentsEnhance v7.1.0 generated an exception while executing task 4757
28.02 18:53:22 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: -1
28.02 18:53:22 [Server] INFO at java.util.ArrayList.fastRemove(ArrayList.java:546) ~[?:1.8.0_144]
28.02 18:53:22 [Server] INFO at java.util.ArrayList.remove(ArrayList.java:529) ~[?:1.8.0_144]
28.02 18:53:22 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerInventory.onClose(PlayerInventory.java:51) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at net.minecraft.server.v1_13_R2.Container.transferTo(Container.java:38) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1192) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at net.minecraft.server.v1_13_R2.EntityPlayer.closeInventory(EntityPlayer.java:1031) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:517) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu$3.run(MainMenu.java:267) ~[?:?]
28.02 18:53:22 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
28.02 18:53:22 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
28.02 18:53:22 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
28.02 18:53:22 [Server] WARN [EnchantmentsEnhance] Plugin EnchantmentsEnhance v7.1.0 generated an exception while executing task 4722
28.02 18:53:22 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: -1
28.02 18:53:22 [Server] INFO at java.util.ArrayList.add(ArrayList.java:459) ~[?:1.8.0_144]
28.02 18:53:22 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerInventory.onOpen(PlayerInventory.java:47) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at net.minecraft.server.v1_13_R2.Container.transferTo(Container.java:40) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1192) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at net.minecraft.server.v1_13_R2.EntityPlayer.closeInventory(EntityPlayer.java:1031) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:517) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu$3.run(MainMenu.java:267) ~[?:?]
28.02 18:53:22 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-514]
28.02 18:53:22 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
```

_Originally posted by @25 in https://github.com/25/EnchantmentsEnhance/issues/88#issuecomment-468531048_

**Comment by lgou2w** [comment]
Source: Line 267
```java
player.closeInventory(); 
new ItemMenu(player).open(); 
```
https://github.com/25/EnchantmentsEnhance/blob/60c9abb3f9adb9d36d095e09242f1c3225eacce0/EnchantmentsEnhance-Plugin/src/main/java/org/pixeltime/enchantmentsenhance/gui/menu/MainMenu.java#L263-L279

**Comment by lgou2w** [comment]
Temporary solution 😪
